name: inspiriererin
description: A Discord bot that sends you inspirational quotes from InspiroBot
homepage: https://github.com/pixelcmtd/Inspiriererin
version: 0.2.0

environment:
  sdk: ^3.0.0

executables:
  inspiriererin: inspiriererin

dependencies:
  args: ^2.3.1
  inspirobot: ^1.0.0
  nyxx: ^5.0.0
  prometheus_client: ^1.0.0
  prometheus_client_shelf: ^1.0.0
  shelf: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
