name: Inspiriererin
description: A Discord bot
version: 1.0.0
homepage: https://github.com/chrissxYT/Inspiriererin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  nyxx: ^2.0.0-rc.3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
