name: Inspiriererin
description: A Discord bot
homepage: https://github.com/chrissxYT/Inspiriererin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  nyxx: ^2.0.0-rc.7

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
