name: Inspiriererin
description: A Discord bot
homepage: https://github.com/pixelcmtd/Inspiriererin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  inspirobot: ^1.0.0
  nyxx: ^3.2.7
  prometheus_client: ^1.0.0
  prometheus_client_shelf: ^1.0.0
  shelf: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
